{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pkgload
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pkgload_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pkgload/pkgload_{{ version }}.tar.gz
  sha256: 09e4885e9cc25af29063a525da0b2ac9dd66fc7a95ea085bf5060312e3a67549

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.3.0
    - r-crayon
    - r-desc
    - r-fs
    - r-glue
    - r-pkgbuild
    - r-rlang >=1.1.1
    - r-rprojroot
    - r-withr >=2.4.3
  run:
    - r-base
    - r-cli >=3.3.0
    - r-crayon
    - r-desc
    - r-fs
    - r-glue
    - r-pkgbuild
    - r-rlang >=1.1.1
    - r-rprojroot
    - r-withr >=2.4.3

test:
  commands:
    - $R -e "library('pkgload')"           # [not win]
    - "\"%R%\" -e \"library('pkgload')\""  # [win]

about:
  home: https://github.com/r-lib/pkgload
  license: GPL-3.0-only
  summary: Simulates the process of installing a package and then attaching it. This is a key part of the 'devtools' package as it allows you to rapidly iterate while developing a package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
