{% set version = "1.3.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pkgload
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pkgload_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pkgload/pkgload_{{ version }}.tar.gz
  sha256: b0898122876479cc4a35cd566654b3a7b50f8ac105565dbf3f8b9d4283816959

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.3.0
    - r-crayon
    - r-desc
    - r-fs
    - r-glue
    - r-rlang >=1.0.3
    - r-rprojroot
    - r-withr >=2.4.3
  run:
    - r-base
    - r-cli >=3.3.0
    - r-crayon
    - r-desc
    - r-fs
    - r-glue
    - r-rlang >=1.0.3
    - r-rprojroot
    - r-withr >=2.4.3

test:
  commands:
    - $R -e "library('pkgload')"           # [not win]
    - "\"%R%\" -e \"library('pkgload')\""  # [win]

about:
  home: https://github.com/r-lib/pkgload
  license: GPL-3.0-only
  summary: Simulates the process of installing a package and then attaching it. This is a key part of the 'devtools' package as it allows you to rapidly iterate while developing a package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pkgload
# Title: Simulate Package Installation and Attach
# Version: 1.0.2
# Authors@R: c( person("Hadley", "Wickham", role = "aut"), person("Jim", "Hester", , "james.hester@rstudio.com", role = c("aut", "cre")), person("Winston", "Chang", role = "aut"), person("RStudio", role = "cph"), person("R Core team", role = "ctb", comment = "Some namespace and vignette code extracted from base R") )
# Description: Simulates the process of installing a package and then attaching it. This is a key part of the 'devtools' package as it allows you to rapidly iterate while developing a package.
# License: GPL-3
# URL: https://github.com/r-lib/pkgload
# BugReports: https://github.com/r-lib/pkgload/issues
# Imports: desc, methods, pkgbuild, rlang, rprojroot, rstudioapi, utils, withr
# Suggests: bitops, covr, Rcpp, testthat
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.0
# NeedsCompilation: yes
# Packaged: 2018-10-29 19:56:19 UTC; jhester
# Author: Hadley Wickham [aut], Jim Hester [aut, cre], Winston Chang [aut], RStudio [cph], R Core team [ctb] (Some namespace and vignette code extracted from base R)
# Maintainer: Jim Hester <james.hester@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-10-29 20:30:03 UTC
